name: functional_tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install requirements
        run: python -m pip install -r tests/requirements.txt     
      - name: output tests
        run: python tests/output.py
      - name: session generation tests
        run: python tests/session_generation.py